kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
  name: employee-backend 
  namespace: turquoise
  labels:
    app: employee-backend
    app.kubernetes.io/component: employee-backend
    app.kubernetes.io/instance: employee-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: employee-backend
  template:
    metadata:
      labels:
        deployment: employee-backend
    spec:
      containers:
        - name: employee-backend
          image: 'image-registry.openshift-image-registry.svc:5000/turquoise/employee-backend:latest'
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%