kind: Service
apiVersion: v1
metadata:
  name: employee-backend
  namespace: turquoise
  labels:
    app: employee-backend
    app.kubernetes.io/component: employee-backend
    app.kubernetes.io/instance: employee-backend  
spec:
 
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
  selector:
    deployment: employee-backend
